docs/BSC-fast-node.md

Fix incorrect description of insecure-prune-all command

fix: incorrect cmd for insecure-prune-all

---

docs/chainide.md

Hi
Since we update our S3 bucket, so we open this pr to update chainide docs image links

Update chainide doc s3 links

---

docs/beaconchain/governance.md
docs/beaconchain/learn/bsc-gov.md
docs/learn/bsc-gov-workflow.md
docs/learn/bsc-gov.md

The threshold for submitting a proposal is **2000BNB** for both testnet and mainnet.

update the deposit amount for a proposal from 1K to 2K

---

docs/beaconchain/learn/escrow-accounts.md
sidebars.js

add addresses of bc escrow accounts

add document for bc escrow accounts

---

docs/overview.md

This PR refine the overview of bnb chain,
Some changes here:
1. The `side chain` is removed from the ecosystem.
2. Refine the description for each component.
The figure still contains a side chain, we will delete it in a later PR.

overview: remove side chain from the ecosystem

---

docs/beaconchain/faq/faq.md
docs/beaconchain/index.md
docs/beaconchain/learn/BEP8.md
docs/learn/beaconIntro.md

Dex feature had been removed from Beacon Chain. In this pr, some description about dex is removed or updated.
There will be other prs to further clean up dex related docs and apis.
No
- update general description about beacon chain

[R4R] doc: remove docs about dex

---

docs/learn/intro.md

The current introduction about BSC is too simple, this PR aims to rich the content.
NO
More contend for the BSC introduction

docs: refine the introduction for BSC

---

docs/add-account.md
docs/beaconchain/chain-access.md
docs/beaconchain/learn/atomic-swaps.md
docs/beaconchain/learn/encoding/amino-example.md
docs/dev-tools.md
docs/getting-started.md
docs/migration/evm-chains/chain-comparison.md
docs/wallet/arkane-developer.md
docs/wallet/extension/add-account.md
docs/wallet/ledger.md

This pr will fix some spelling issues in the documents.
No
No

doc: fix typos in documents

---

docs/beaconchain/develop/node/fullnode-faq.md
docs/beaconchain/develop/node/fullnodeissue.md
docs/beaconchain/develop/node/upgrade.md
docs/beaconchain/fullnodeissue.md
docs/beaconchain/governance.md
docs/fullnodeissue.md

The `state recover` tool can be downloaded along each release now. This pr will update the links for downloading the tool.
No
No

doc: update link for downloading state reover tool

---

docs/learn/beaconIntro.md

This pr updates the introduction of Beacon Chain to make it simple. 
Because some related contents are covered in BSC side, e.g., cross chain, so there is no need to put them here.
No
- introduction of beacon chain

doc: rewrite beacon chain intro

---

docs/beaconchain/learn/genesis.md

This pr re-org and update the content of `genesis file` document.
No
- genesis file doc

doc: update doc of genesis file

---

docs/beaconchain/governance.md
docs/learn/bsc-gov.md

This pr re-org and update the content of `beacon chain governance` document.
No
-  update beacon chain `governance` doc
- small fix of smart chain `governance` doc

doc: update content of governance

---

docs/zkbnb/zkbnb-architecture.md
docs/zkbnb/zkbnb-faqs.md
docs/zkbnb/zkbnb-overview.md
docs/zkbnb/zkbnb-storageLayout.md
docs/zkbnb/zkbnb-tokenomics.md
docs/zkbnb/zkbnb-wallets.md
sidebars.js

- Added new zkBNB FAQ page
- ZkBNB to zkBNB spelling corrections

Add zkBNB FAQ page

---

docs/zkbnb/zkbnb-architecture.md
docs/zkbnb/zkbnb-faqs.md
docs/zkbnb/zkbnb-overview.md
docs/zkbnb/zkbnb-storageLayout.md
docs/zkbnb/zkbnb-tokenomics.md
docs/zkbnb/zkbnb-wallets.md
sidebars.js

Added new zkBNB FAQ page
ZkBNB to zkBNB spelling corrections

Added new zkBNB FAQ page

---

docs/beaconchain/validator/create-val.md
docs/beaconchain/validator/overview.md
docs/beaconchain/validator/run-val.md
sidebars.js

This pr adds steps for running BC validators.
No
-  update beacon chain  docs

docs: add beacon chain run validator docs

---

docs/beaconchain/develop/api-reference/dex-api/staking.md

This pr will update the document of staking api, to include the `min` and `max` values of `offset`/`limit` parameters.

docs: update staking api for offset and limit

---

docs/validator/overview.md
docs/validator/send-slash-evidence.md

1. add the description of ff rewards and penalties in the overview of validators
2. add descriptions about malicious vote monitoring and evidence submission tools

update reward and slash for fast finality

---

docs/beaconchain/develop/api-reference/dex-api/paths-testnet.md
docs/beaconchain/develop/api-reference/dex-api/paths.md
docs/beaconchain/develop/api-reference/node-rpc.md
docs/beaconchain/faq/faq.md
docs/dev-outlook-2022.md
docs/migration/non-evm-chains/solana/token-migration.md
docs/tokens.md
docs/validator/send-slash-evidence.md
docs/validator/unjail.md
docs/wallet/binance-cn.md
docs/wallet/binance.md
docs/wallet/ledger.md
docs/wallet/math.md
docs/wallets/tutorial/bep8.md
static/api-swagger/index.html

*Changes*
- Update all Binance Chain to BNB Chain
- Update all Binance Smart Chain to BNB Smart Chain

docs: update brand name

---

docs/learn/ecosystem.md

Removed Multichain from supported cross chain bridges

Updated cross chain bridges in ecosystem.md

---

docs/wallet/metamask.md

Updated the metamask tutorial to include how to set the max base fee and priority fee.

Update metamask tutorial for BNB transfer

---

docs/wallet/metamask.md

fixed image size in metamask tutorial

---

docs/learn/ecosystem.md

Added Moralis as NFT API provider on the ecosystem page

Added Moralis as NFT API provider

---

docs/validator/fullnode.md
docs/validator/node-maintenance.md
docs/validator/run-val.md

- Updated hardware specs for running bsc full node.
- Ref: 
- https://github.com/bnb-chain/bsc/tree/develop?tab=readme-ov-file#hardware-requirements
- https://docs.bnbchain.org/docs/validator/run-val#2-testnet

Update hardware specs for running bsc mainnet/testnet full node

---

docs/learn/ecosystem.md

Hello BNB team,
We are submitting this contribution with the intention of incorporating SubQuery into your project documentation. As you can observe, we have already prepared the initial project. Kindly inform us if any adjustments are necessary on our part.

Added SubQuery to `ecosystem.md`

---

docs/BSC-FAQs-validator.md

- added validator FAQ for getting err `can't start mining w/o etherbase`

added validator FAQ for getting err `can't start mining w/o etherbase`

---

docs/BSC-FAQs-general.md

- added faq for starting/stopping bsc node as a service.

added faq for starting/stopping bsc node as a service

---

docs/bcfusion/validators/key-managment.md
docs/bcfusion/validators/keyt-managment.md

add docs for BSC key management after BC sunset

docs: add docs for BSC key management

---

docs/bcfusion/developers/crosschain-redelegation.md
docs/bcfusion/developers/gov.md
docs/bcfusion/developers/staking.md
docs/bcfusion/validators/gov.md
docs/bcfusion/validators/slash.md
docs/bcfusion/validators/staking.md
sidebars.js

do not need to merge now
it is preparation

docs: add docs for BSC staking and gov

---

docs/archivenode.md
docs/parameters.md
docs/validator/create-val.md
docs/validator/overview.md
sidebars.js

Update
1. self-delegation stake amount for testnet
2. offline slashing description
3. deprecate archive node support with Geth client
4. sidebar "Future Developers" to "BSC Roadmap"

Update information on docs

---

docs/BSC-fast-node.md
docs/BSC-verify-node.md
docs/validator/fullnode.md
docs/validator/node-maintenance.md
docs/validator/upgrade-fullnode.md

from --txlookuplimit to --history.transactions

update node start-up command flag 

---

docs/Wallet.md
sidebars.js

insert Binance web3 wallet.
From sidebar.js,  shift "wallet" to under "Develop" subsection, above "Tools"

Update wallet list

---

docs/learn/ecosystem.md
docs/validator/docker.md
sidebars.js

sidebars.js:
change "wallet" directory, hide "tools" content from ecosystem.md, insert developer tooling landscape URL
docker.md:
update issue https://github.com/bnb-chain/bsc/issues/2289

Update sidebars.js, docker.md and ecosystem.md

---

docs/bcfusion/validators/migrations.md

streamline docs for validator migration

docs: update validator migration docs

---

docs/wallet/venly.md

Updated name and sidebar label

Update and rename arkane.md to venly.md

---

docs/bcfusion/users/gov.md

docs: update tally url for mainnet

---

docs/bcfusion/developers/staking.md
docs/bcfusion/users/stake-migration.md

docs: add stake migration video

---

docs/bnb-opbnb/advanced/local-dev-env.md

Update the document to match the latest code.

opbnb: update local development env doc

---

docs/announce/index.md
docs/announce/second-sunset-bc-testnet.md
mkdocs.yml

add announcement for BC testnet second sunset hardfork

docs: add announcement for BC testnet second sunset hardfork

---

.gitignore
docs/announce/index.md
docs/announce/second-sunset-bc.md
mkdocs.yml

docs: add announcement for BC mainnet second sunset hardfork

docs: add announcement for BC mainnet second sunset hardfork

---

docs/bnb-greenfield/core-concept/cross-chain/interface.md
docs/bnb-greenfield/core-concept/cross-chain/sdk.md

This pr is to update greenfield cross-chain docs

Update greenfield cross-chain docs

---

docs/announce/final-sunset-bc-testnet.md
docs/announce/index.md
mkdocs.yml

add announcement for bc testnet final sunset hardfork

docs: announcement for bc testnet final sunset hardfork

---

docs/announce/index.md
docs/bc-fusion/overview.md
mkdocs.yml

docs: move announcement for bc testnet final sunset hardfork

---

docs/announce/bohr-bsc.md
docs/announce/index.md
mkdocs.yml

And Mongolian Hardfork(Greenfield) has passed

docs: update announcement for bsc bohr hardfork

---

docs/bnb-smart-chain/staking/developer-guide.md

add code example for staking reward

chore: add code example for staking reward

---

docs/announce/final-sunset-bc-mainnet.md
docs/announce/index.md
mkdocs.yml

add new hardfork announcement & cleanup

chore: add new hardfork announcement & cleanup

---

docs/announce/index.md
docs/announce/savanna-greenfield.md
mkdocs.yml

update savanna-greenfield hardfork in announcement

doc: update savanna-greenfield hardfork in announcement

---

docs/bnb-smart-chain/benchmark/design-reference.md
mkdocs.yml

add BSC benchmark design reference to doc site

add benchmark design reference doc
