bnb-chain/bnb-chain.github.io

docs/validator/fullnode.md
It used to say "geth <parameters>" which on machines where geth is installed causes users to use the local install (and therefore the wrong version), and on machines where geth is not installed, just causes an error to happen.
=> Reduce confusion about which command to use.

docs/BSC-FAQs-validator.md, docs/BSC-verify-node.md, docs/validator/fullnode.md, docs/validator/node-maintenance.md, docs/validator/upgrade-fullnode.md
The diff sync mode is deprecated because BSC supports fastnode mode which is more efficient, so let us remove it from the document.
=> node: remove diffsync flag

docs/beaconchain/learn/escrow-accounts.md
fix wrong peg account addresses (which is caused by copy & paste)
=> fix escrow account address of peg accounts

docs/getting-started.md, sidebars.js, src/pages/index.js
The get started chapter should be quite simple and straightforward for new users, while the current version contains too much useless or high-level info, this PR aims to delete it.
No
TODO: we will rewrite the get started docs in short future.
=> fix:  remove improper content in the get started part 

docs/learn/consensus.md
The docs about BSC consensus engine are a bit messy, this PR tries to refine it.
1. Too many introductions about the implementation details, which is not user friendly.
2. Give more introduction about the hight level structure.
No.
=> docs: refine the structure of consensus engine

docs/BSC-fast-node.md, docs/BSC-separate-node.md
Update `docs/BSC-fast-node.md` and `docs/BSC-separate-node.md` to note that fast nodes can never revert to full node.
=> Note that fast nodes can never revert to full node

docs/beaconchain/learn/accounts.md, docs/beaconchain/learn/architecture.md
This pr update the content of `beacon chain architecture` to make it easier to follow and more related to *architecture*.
No
-  update beacon chain `architecture`  and `account` doc
=> doc: update the architecture doc of beacon chain

docs/beaconchain/learn/breathe-block.md, sidebars.js
This pr adds the content of `beacon breathe blocks`. 
In beacon chain, breathe block is a very important concept and it will help readers to better understand beacon chain.
No
-  add beacon chain `breathe block` doc
=> doc: add document for breathe blocks

docs/dstorages.md, docs/learn/ecosystem.md, docs/nft-storage.md, sidebars.js
For Issue https://github.com/bnb-chain/bnb-chain.github.io/issues/75.
- Add a tutorial for storage NFT assets on IPFS/Filecoin using [NFT.storage](http://nft.storage/) under `BNB Smart Chain -> Develop -> Deploy NFTs on BSC`.
=> add NFT.Storage tutorial

docs/beaconchain/develop/node/join-mainnet.md, docs/beaconchain/develop/node/join-testnet.md
This pr adds steps for running BC nodes by using snapshot.
The page of BC snapshot is: https://github.com/bnb-chain/bc-snapshots 
No
-  update beacon chain  docs
=> doc: add steps for setup bc nodes with snapshot

docs/validator/fullnode.md
The previous link `https://github.com/bnb-chain/bsc-deploy` is a private repo, now change to `https://github.com/bnb-chain/node-deploy` which is public.
=> docs: fix the wrong link about bsc deploy tool

docs/beaconchain/validator/run-val.md
This pr updates the spec for running beacon chain validators. 
The previous requirement in the docs is too high.
No
-  update spec for running bc valdiators
=> docs: update spec for running bc validators

docs/BSC-FAQs-general.md, docs/BSC-FAQs-validator.md, docs/BSC-FAQs.md, docs/parameters.md, docs/validator/create-val.md, docs/validator/overview.md, docs/validator/unjail.md
- Update minimum stake for validators from 10,000 to 2,000 BNBs
=> BSC Validator self-stake update

docs/beaconchain/learn/bc-staking.md, docs/stake/cli-commands.md, docs/validator/create-val.md
add description for new flag `bls-wallet` about side vote addr
side-vote-addr is optional for bsc-edit-validator
=> fix: add description for new flag `bls-wallet` about side vote addr

docs/validator/run-val.md
use the first keyfile in `keystore` as etherbase in the past
but validator may need store multi keyfiles in `keystore`, then validator need to change filenames
by requiring explicit etherbase address, avoiding the need to change filenames
=> validator require explicit etherbase address

docs/validator/fullnode.md
- Updated and added `--state.scheme path` for PBSS in steps
- Added more notes, tips and caution as per new changes w.r.t. v1.2.15 and v1.3.4 versions
- References:
-  https://github.com/bnb-chain/bsc/blob/63824a835d0a774732705dec7d6e4f5b4dc58f73/README.md#3-download-snapshot
- https://www.bnbchain.org/en/blog/hotfix-hardfork-for-bsc-testnet-and-mainnet
- Updated hardware requirements for running bsc mainnet full node.
- Added hardware requirements for running bsc testnet full node.
=> Updated Steps (and HW specs) for running BSC node with PBSS and additional notes, tips/caution

docs/BSCtestnet.md, docs/ERC721.md, docs/beaconchain/develop/testnetandexplorer.md, docs/bnb-chain-wallet.md, docs/bsc-faucet.md, docs/chainide.md, docs/getting-started.md, docs/learn/ecosystem.md, docs/migration/evm-chains/token-migration.md, docs/migration/non-evm-chains/solana/token-migration.md, docs/nft_blackide.md, docs/remix-new.md, docs/replit.md, docs/wallet/AlphaWallet.md, docs/wallet/binance-cn.md, docs/wallet/bnb-chain-wallet.md, docs/wallet/math.md
- Updated BSC testnet faucet URL to `https://www.bnbchain.org/en/testnet-faucet`
- Faucet link: https://www.bnbchain.org/en/testnet-faucet
=> Updated BSC testnet faucet URL

docs/validator/best-practice.md
- added `Peers configuration` notes for mainnet and testnet in node's best-practise.
- added `troubleshooting for no peers in testnet` section in node's best-practise.
=> Added Peers configuration note and Troubleshooting no peers in testnet section.

docs/BSC-fast-node.md, docs/BSC-separate-node.md, docs/BSC-verify-node.md, docs/boot-nodes.md, sidebars.js
- moved files from `Nodes` section to `Running BSC Nodes` section and renamed their sibebar labels
- Renamed Sidelabes as below:
- Fast Node -> BNB Smart Chain Fast Node
- Verify Node -> BNB Smart Chain Verify Node
- Separate Node -> BNB Smart Chain Separate Node
-  Boot Nodes -> BNB Smart Chain Boot Nodes
- Removed `Nodes` category from sidebar.js and moved its items to `Running BSC Nodes` category.
=> Merged `Nodes` into `Running BSC Nodes` section and re-labelled fast node sidebar labels.

docs/rpc.md
Moralis has re-launched its node product. So added it back to node provider list.
=> Added back moralis as RPC provider

docs/bc_fusion/overview.md, docs/bc_fusion/users/gov.md
=> chore: fix doc issue in gov

docs/bnb-greenfield/getting-started/wallet-configuration.md, docs/bnb-greenfield/storage-provider/workflow.md
Some image links are broken when migrate from greenfield docs.
=> fix: broken image link migrate from greenfield docs

docs/bnb-smart-chain/developers/json_rpc_apis/finality-api.md
format not expected
this PR is to solve this issue
=> fix param description format for finality apis

docs/bnb-smart-chain/developers/node_operators/archive_node.md, docs/bnb-smart-chain/developers/node_operators/erigon_node.md, mkdocs.yml
=> update erigon doc

docs/bc-fusion/overview.md, docs/bc-fusion/post-fusion/faq.md, mkdocs.yml, overrides/main.html
the docs are not deleted yet, for there are links to them. just do not show them in the nav.
=> chore: refine docs after bc fusion

docs/bnb-smart-chain/developers/node_operators/fast_node.md
=> remove verify node related

docs/bnb-smart-chain/slashing/monitor.md, docs/bnb-smart-chain/slashing/slash-rules.md
with shorter block interval, these values could be updated.
=> doc: update the number of misdemeanorThreshold and felonyThreshold
